export const SET_DIRECTION = 'SET_DIRECTION';
export const RESET_DIRECTION = 'RESET_DIRECTION';

export const ADD_FAVORITE_TERM = 'ADD_FAVORITE_TERM';
export const REMOVE_FAVORITE_TERM = 'REMOVE_FAVORITE_TERM';
export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';